name: Run Postman Collection

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Run Postman collection
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        run: |
          postman login --with-api-key $POSTMAN_API_KEY
          postman collection run "$COLLECTION_ID" \
            --reporters cli,json \
            --reporter-json-export results.json

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: postman-results
          path: results.json
